DROP TABLE IF EXISTS `%TABLE_PREFIX%redactor_profiles`;

CREATE TABLE IF NOT EXISTS `%TABLE_PREFIX%redactor_profiles` (
  `id` int(11) unsigned NOT NULL auto_increment,
  `name` varchar(30) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  `lang` varchar(10) NOT NULL default '',
  `configuration` text NOT NULL default '',
  `ptype` tinyint(4) NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM;

--
--
--

INSERT INTO `%TABLE_PREFIX%redactor_profiles` VALUES(1, 'css', 'CSS fuer den Redactor', '', '/* ---------------------- */\r\n/* Redactor specific rules */\r\n/* ---------------------- */\r\n', 1);
INSERT INTO `%TABLE_PREFIX%redactor_profiles` VALUES(2, 'default', 'Standard Redactor-Konfiguration', 'de', 'buttonsCustom:{\r\n	rex_image:{\r\n		title: ''Bild einfügen'', \r\n		callback: rex_redactor_image\r\n	},\r\n	rex_media:{\r\n		title: ''Dateilink'', \r\n		dropdown:{\r\n			rex_media_ins:{\r\n				title: ''Dateilink einfügen ...'',\r\n				callback: rex_redactor_media_ins\r\n			},\r\n			rex_media_del:{\r\n				title: ''Dateilink entfernen'',\r\n				exec: ''unlink''\r\n			}\r\n		}\r\n	},\r\n	rex_link:{\r\n		title: ''Interner Link'', \r\n		dropdown:{\r\n			rex_link_ins: {\r\n				title: ''Internen Link einfügen ...'',\r\n				callback: rex_redactor_link_ins\r\n			},\r\n			rex_link_del:{\r\n				title: ''Internen Link entfernen'',\r\n				exec: ''unlink''\r\n			}\r\n		}\r\n		\r\n	}\r\n},\r\n\r\nbuttons: [\r\n	''formatting'', ''|'',\r\n	''bold'', ''italic'', ''deleted'', ''|'',\r\n	''unorderedlist'', ''orderedlist'', ''outdent'', ''indent'', ''|'',\r\n	''alignment'', ''|'',\r\n	''link'', ''rex_link'', ''rex_image'', ''rex_media'', ''|'',\r\n	''horizontalrule'', ''|'', \r\n	''html'' \r\n	],\r\n\r\nfocus: false,\r\nautoresize: false,\r\ncleanup: true,\r\nconvertLinks: false,\r\nfixedBox: true,\r\nwym: false,\r\nplugins: [''fullscreen''],\r\n\r\nrex_linktitle: true,\r\nrex_mediatitle: true,\r\nrex_filetitle: true,\r\n', 0);
INSERT INTO `%TABLE_PREFIX%redactor_profiles` VALUES(3, 'full', 'Redactor-Konfiguration mit allen Funktionen', 'de', 'buttonsCustom:{\r\n	rex_image:{\r\n		title: ''Bild einfügen'', \r\n		callback: rex_redactor_image\r\n	},\r\n	rex_media:{\r\n		title: ''Dateilink'', \r\n		dropdown:{\r\n			rex_media_ins:{\r\n				title: ''Dateilink einfügen ...'',\r\n				callback: rex_redactor_media_ins\r\n			},\r\n			rex_media_del:{\r\n				title: ''Dateilink entfernen'',\r\n				exec: ''unlink''\r\n			}\r\n		}\r\n	},\r\n	rex_link:{\r\n		title: ''Interner Link'', \r\n		dropdown:{\r\n			rex_link_ins:{\r\n				title: ''Internen Link einfügen ...'',\r\n				callback: rex_redactor_link_ins\r\n			},\r\n			rex_link_del:{\r\n				title: ''Internen Link entfernen'',\r\n				exec: ''unlink''\r\n			}\r\n		}\r\n		\r\n	}\r\n},\r\n\r\nbuttons:[\r\n	''formatting'', ''|'',\r\n	''bold'', ''italic'', ''deleted'', ''|'',\r\n	''unorderedlist'', ''orderedlist'', ''outdent'', ''indent'', ''|'',\r\n	''fontcolor'', ''backcolor'', ''|'', \r\n	''alignment'', ''|'',\r\n	''link'', ''rex_link'', ''rex_image'', ''rex_media'', ''video'', ''|'',\r\n	''table'', ''|'', ''horizontalrule'', ''|'', \r\n	''html'' \r\n	],\r\n	\r\nfocus: false,\r\nautoresize: false,\r\ncleanup: true,\r\nconvertLinks: false,\r\nfixedBox: true,\r\nwym: false,\r\nplugins: [''fullscreen''],\r\n\r\ncolors:[\r\n	''#ffffff'', ''#000000'', ''#eeece1'', ''#1f497d'', ''#4f81bd'', ''#c0504d'', ''#9bbb59'', ''#8064a2'', ''#4bacc6'', ''#f79646'', ''#ffff00'',\r\n	''#f2f2f2'', ''#7f7f7f'', ''#ddd9c3'', ''#c6d9f0'', ''#dbe5f1'', ''#f2dcdb'', ''#ebf1dd'', ''#e5e0ec'', ''#dbeef3'', ''#fdeada'', ''#fff2ca'',\r\n	''#d8d8d8'', ''#595959'', ''#c4bd97'', ''#8db3e2'', ''#b8cce4'', ''#e5b9b7'', ''#d7e3bc'', ''#ccc1d9'', ''#b7dde8'', ''#fbd5b5'', ''#ffe694'',\r\n	''#bfbfbf'', ''#3f3f3f'', ''#938953'', ''#548dd4'', ''#95b3d7'', ''#d99694'', ''#c3d69b'', ''#b2a2c7'', ''#b7dde8'', ''#fac08f'', ''#f2c314'',\r\n	''#a5a5a5'', ''#262626'', ''#494429'', ''#17365d'', ''#366092'', ''#953734'', ''#76923c'', ''#5f497a'', ''#92cddc'', ''#e36c09'', ''#c09100'',\r\n	''#7f7f7f'', ''#0c0c0c'', ''#1d1b10'', ''#0f243e'', ''#244061'', ''#632423'', ''#4f6128'', ''#3f3151'', ''#31859b'', ''#974806'', ''#7f6000''\r\n	],\r\n\r\nrex_linktitle: true,\r\nrex_mediatitle: true,\r\nrex_filetitle: true,\r\n', 0);
